FROM ubuntu:18.04

# RUN apt-get update
# RUN apt-get install -y texlive-xetex

# Install Roboto font
# RUN apt-get install -y fonts-roboto


# copy the current directory contents into the container at /app
COPY . /app

# Set the working directory to /app
WORKDIR /app